meta_product_name: "Randomize"
meta_title: "Randomize - Laisse-toi surprendre !"
meta_description: "Découvre des activités auxquelles tu n'aurais jamais pensé près de chez toi. C'est facile, appuie sur Randomize !"
meta_image: "lille.jpg" # should exist in `app/assets/images/`
